# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0002_wish_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(default=None),
        ),
    ]
