# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0003_wish_granted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 59, 55, 484367)),
        ),
    ]
