# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0004_auto_20181022_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
