# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0005_auto_20181022_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 10, 22, 12, 5, 19, 787836)),
            preserve_default=False,
        ),
    ]
