# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0006_auto_20181022_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='granted_at',
        ),
    ]
